name: BlockChange
main: me.insanj.BlockChanger.BlockChanger
author: KattyKate
version: 1.1
commands: /blockchange 
  BlockChanger:
    description: Change any block!!!!
    permissions: BlockChange.Change
    usage: /blockchange <block>
